name: 'Upload image'
description: 'Uploads an image and returns a url to it.'
branding:
  icon: 'upload'  
  color: 'gray-dark'
inputs:
  path:
    description: 'Path(s) to the image(s) to upload.'
    required: true
  uploadMethod:
    description: 'Where to upload images.'
    required: true
    default: 
  apiKey:
    description: 'API if the upload method needs it.'
    required: true
    default: ''
  expiration:
    description: 'How long the image(s) should be available is seconds.'
    required: false
outputs:
  url:
    description: 'A URL of the uploaded image. If multiple images are uploaded, each URL is returned in a new line.'
  urls:
    description: 'Same as url, but as an array of URLs of the uploaded images.'
  expiration:
    description: 'When the image expires in seconds. If multiple images are uploaded, each expiration is returned in a new line.'
runs:
  using: 'node20'
  main: 'dist/index.js'