# An example of a workflow that uses McCzarny/upload-image action.
name: Example of upload-image action where it is used to upload an image and then delete it.
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  # This job uploads an image, prints info about it, and keeps the delete URL as an artifact.
  upload-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Upload image
      id: upload-image-step
      uses: ./
      with:
        apiKey: ${{ env.API_KEY }}
        path: ./test-resources/2.png
        uploadMethod: imgbb
    - name: print-uploaded-image-info
      run: |
        echo "Image URL: ${{ steps.upload-image-step.outputs.url }}"
        echo "Image delete URL: ${{ steps.upload-image-step.outputs.delete_url }}"
        echo "Image expiration in seconds: ${{ steps.upload-image-step.outputs.expiration }}"
    # Using delete_urls instead of delete_url as it is stored as an array by the action.
    # Use single quotes in echo because array value are quoted.
    - name: Keep delete URL in a file
      run: |
        echo '${{ steps.upload-image-step.outputs.delete_urls }}' > delete-url.json
        echo "Content of delete-url.json:"
        cat delete-url.json
    - name: Keep delete URL as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: delete-url
        path: delete-url.json
  # This job deletes the image uploaded by the previous job using the delete URL stored in the artifact.
  delete-image:
    runs-on: ubuntu-latest
    needs: upload-image
    steps:
    - uses: actions/checkout@v4
    - name: download-delete-url
      uses: actions/download-artifact@v4
      with:
        name: delete-url
    - name: Get delete URL from the artifact
      id: get-delete-url
      run: |
        ls -la .
        delete_url=$(cat delete-url.json)
        echo "Delete URL: $delete_url"
        echo "delete_url=$delete_url" >> $GITHUB_OUTPUT
    # Delete the image using delete-imgbb-image action.
    - name: delete-image
      id: delete-image-step
      uses: ./delete-imgbb-image