# An example of a workflow that uses McCzarny/upload-image action.
name: Example of upload-image action where it is used to upload an image and then delete it.
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  # This job uploads an image, prints info about it, and keeps the delete URL as an artifact.
  upload-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Upload image
      id: upload-image-step
      uses: ./
      with:
        apiKey: ${{ env.API_KEY }}
        path: ./test-resources/2.png
        uploadMethod: imgbb
    - name: print-uploaded-image-info
      run: |
        echo "Image URL: ${{ steps.upload-image-step.outputs.url }}"
        echo "Image delete URL: ${{ steps.upload-image-step.outputs.delete_url }}"
        echo "Image expiration in seconds: ${{ steps.upload-image-step.outputs.expiration }}"
    # Using delete_urls instead of delete_url as it is stored as an array by the action.
    # Use single quotes in echo because array value are quoted.
    - name: Keep delete URL in a file
      run: |
        echo '${{ steps.upload-image-step.outputs.delete_urls }}' > delete-url.json
        echo "Content of delete-url.json:"
        cat delete-url.json
    - name: Keep delete URL as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: delete-url
        path: delete-url.json
  # This job deletes the image uploaded by the previous job using the delete URL stored in the artifact.
  delete-image:
    runs-on: ubuntu-latest
    needs: upload-image
    steps:
    - uses: actions/checkout@v4
    - name: download-delete-url
      uses: actions/download-artifact@v3
      with:
        name: delete-url
    - name: Get delete URL from the artifact
      id: get-delete-url
      run: |
        ls -la .
        delete_url=$(cat delete-url.json)
        echo "Delete URL: $delete_url"
        echo "delete_url=$delete_url" >> $GITHUB_OUTPUT
    # Delete the image using imgbb internal API. It should be replaced with a dedicated action in the future.
    - name: delete-image
      run: |
        id=$(echo ${{ fromJson(steps.get-delete-url.outputs.delete_url)[0] }} | cut -d'/' -f4)
        hash=$(echo ${{ fromJson(steps.get-delete-url.outputs.delete_url)[0] }} | cut -d'/' -f5)
        echo "ID: $id / Hash: $hash"
        curl --request POST \
        --url https://ibb.co/json \
        --header 'accept: application/json, text/javascript, */*; q=0.01' \
        --header 'content-type: application/x-www-form-urlencoded; charset=UTF-8' \
        --header 'origin: https://ibb.co' \
        --header 'sec-fetch-dest: empty' \
        --header 'sec-fetch-mode: cors' \
        --header 'sec-fetch-site: same-origin' \
        --header 'sec-gpc: 1' \
        --header 'x-requested-with: XMLHttpRequest' \
        --data auth_token=$API_KEY \
        --data pathname=/$id/$hash \
        --data action=delete \
        --data delete=image \
        --data from=resource \
        --data-urlencode deleting%5Bid%5D=$id \
        --data-urlencode deleting%5Btype%5D=image \
        --data-urlencode deleting%5Bprivacy%5D=public \
        --data-urlencode deleting%5Bhash%5D=$hash
        echo "Status: $?"
